### ISSUE TITLE
start

### ISSUE THREAD

**Issue by dylnmc** [Shougo/deoppet.nvim#1]
my issue is that you have not started development yet.

*looks around nonchalantly* :eyes: *and whistles*

It does say "Issues" ... :smirk:

**Comment by Shougo** [comment]
Yes, it is the big issue.
But please wait.  I have many issues in the other plugins especially denite.nvim.

I should start the development.

Note: I use the feature to implement it.
https://github.com/neovim/neovim/pull/5031

**Comment by Shougo** [comment]
My VimConf 2017 speak title is "deoppet.nvim".
So deoppet.nvim is the dark power plugin in 2017.

2015: deoplete.nvim, dein.vim
2016: denite.nvim, deol.nvim
2017: deoppet.nvim
2018: defx.nvim, deorise.nvim

**Comment by lfilho** [comment]
You're the man!

**Comment by Shougo** [comment]
I have started the development.

**Comment by dylnmc** [comment]
That was fast. Shougo++ good luck!

**Comment by Shougo** [comment]
It is the vaporware though...

**Comment by Shougo** [comment]
I have started the parser development.

**Comment by Shougo** [comment]
I have restarted the development.

**Comment by ress997** [comment]
Merged https://github.com/neovim/neovim/pull/11356

I'm looking forward to using it soon.

**Comment by Shougo** [comment]
Yes.  I need to restart the development.
