### ISSUE TITLE
Nested Snippets

### ISSUE THREAD

**Issue by fastbodin** [Shougo/deoppet.nvim#13]
I wanted to ask if deoppet will have the functionality to handle nested snippets? I know this was a issue difficult to solve in neosnippets:

https://github.com/Shougo/neosnippet.vim/issues/423

Thank you for all the work you do on this project.

**Comment by Shougo** [comment]
Hm.  I need to test the snippet.

**Comment by Shougo** [comment]
I have fixed nested snippets broken behavior.
