### ISSUE TITLE
deoppet does not expand a snippet with leading or trailing spaces as expected

### ISSUE THREAD

**Issue by e-kwsm** [Shougo/deoppet.nvim#18]
**Warning:  I will close the issue without the minimal init.vim and the reproduction instructions.**

# Problems summary

Try to expand a snippet, e.g. `snippet`, at the cursor position:

1. If a line ends with a snippet trigger and a space (`snippet\s$`), deoppet does not expand it
2. If a line ends with a space, a snippet trigger, a space and any character (`\ssnippet\s.\+$`), deoppet expands it *before* the leading space

## Expected

1. Snippet is expanded before the trailing space
2. Snippet is expanded between the leading and the trailing spaces

## Environment Information

 * plugin version(SHA1): d53915b6b4ebe659ebc15befc4c14ceee8bc8fcd

 * OS: Debian 10.6

 * neovim/Vim version: NVIM v0.5.0-nightly-126-g090551a80

 * `:checkhealth` or `:CheckHealth` result(neovim only):
```

health#nvim#check
========================================================================
## Configuration
  - ERROR: Locale does not support UTF-8. Unicode characters may not display correctly.
    $LANG=C $LC_ALL= $LC_CTYPE=
    - ADVICE:
      - If using tmux, try the -u option.
      - Ensure that your terminal/shell/tmux/etc inherits the environment, or set $LANG explicitly.
      - Configure your system locale.

## Performance
  - OK: Build type: RelWithDebInfo

## Remote Plugins
  - OK: Up to date

## terminal
  - INFO: key_backspace (kbs) terminfo entry: key_backspace=\177
  - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~
  - INFO: $VTE_VERSION='5402'
  - INFO: $COLORTERM='truecolor'

health#provider#check
========================================================================
## Clipboard (optional)
  - WARNING: No clipboard tool found. Clipboard registers (`"+` and `"*`) will not work.
    - ADVICE:
      - :help |clipboard|

## Python 2 provider (optional)
  - WARNING: No Python executable found that can `import neovim`. Using the first available executable for diagnostics.
  - ERROR: Python provider error:
    - ADVICE:
      - provider/pythonx: Could not load Python 2:
          /usr/bin/python2 does not have the "neovim" module. :help |provider-python|
          /usr/bin/python2.7 does not have the "neovim" module. :help |provider-python|
          python2.6 not found in search path or not executable.
          /usr/bin/python does not have the "neovim" module. :help |provider-python|
  - INFO: Executable: Not found

## Python 3 provider (optional)
  - INFO: `g:python3_host_prog` is not set.  Searching for python3 in the environment.
  - INFO: Executable: /usr/bin/python3
  - INFO: Python version: 3.7.3
  - INFO: pynvim version: 0.4.2
  - OK: Latest pynvim is installed.

## Python virtualenv
  - OK: no $VIRTUAL_ENV

## Ruby provider (optional)
  - WARNING: `ruby` and `gem` must be in $PATH.
    - ADVICE:
      - Install Ruby and verify that `ruby` and `gem` commands work.

## Node.js provider (optional)
  - WARNING: `node` and `npm` (or `yarn`) must be in $PATH.
    - ADVICE:
      - Install Node.js and verify that `node` and `npm` (or `yarn`) commands work.

## Perl provider (optional)
  - ERROR: perl provider error:
    - ADVICE:
      - "Neovim::Ext" cpan module is not installed

```

## Provide a minimal init.vim/vimrc with less than 50 lines (Required!)

```vim
set runtimepath+=/path/to/deoppet.nvim
set list  " visualize hard tabs

call deoppet#initialize()
call deoppet#custom#option('snippets_dirs', ['/path/to/neosnippet-snippets/neosnippets'])

imap <C-k>  <Plug>(deoppet_expand)
imap <C-f>  <Plug>(deoppet_jump_forward)
imap <C-b>  <Plug>(deoppet_jump_backward)
smap <C-f>  <Plug>(deoppet_jump_forward)
smap <C-b>  <Plug>(deoppet_jump_backward)
```

## The reproduce ways from neovim/Vim starting (Required!)

Open the following C file:
```c
	printf
	printf	
	printf	//
// the 2nd line has a trailing space
```

Try to expand each `printf` by <kbd>Ctrl</kbd><kbd>k</kbd>.

1. Works as expected
2. `printf` is not expanded
3. `	printf` is expanded as `printf("\|n");	` (`|` is the cursor position)

## Screen shot (if possible)
![printf](https://user-images.githubusercontent.com/11627708/94524693-eb75f880-026d-11eb-93d8-67c85edddfe5.gif)

**Comment by Shougo** [comment]
Reproduced.  But it is hard to fix...
Oh no.

**Comment by e-kwsm** [comment]
Thank you for your work, but the cursor position is wrongly set in expansion of [`lastmod`](https://github.com/Shougo/neosnippet-snippets/blob/886a414e339fe40a47f30da8aa6012a6e0906018/neosnippets/_.snip#L22-L25):
![lastmod](https://user-images.githubusercontent.com/11627708/95001522-bbc84700-0605-11eb-897d-79d41784598c.gif)


The following is expansion (`<C-K>` then `<C-F>`) of C [`function`](https://github.com/Shougo/neosnippet-snippets/blob/886a414e339fe40a47f30da8aa6012a6e0906018/neosnippets/c.snip#L91-L97) and  [`if`](https://github.com/Shougo/neosnippet-snippets/blob/886a414e339fe40a47f30da8aa6012a6e0906018/neosnippets/c.snip#L2-L7), which have placeholders:
![function_if](https://user-images.githubusercontent.com/11627708/95001727-c08dfa80-0607-11eb-8329-fb42fd5c3b1a.gif)

**Comment by Shougo** [comment]
Very hard to fix...
You can send the PR instead :-)

**Comment by Shougo** [comment]
Fixed again.

**Comment by e-kwsm** [comment]
Thank you, it is working.

**Comment by e-kwsm** [comment]
I'm not sure why, but the issue has recurred (Shougo/deoppet.nvim@e6d73b82f7f558fc6f51640fee0971cbd5065bbd, neovim/neovim@eaee3d9297d114c81b05dd4ed104373eeb87bc11).

A patch is as follows:
```diff
--- a/autoload/deoppet/util.vim
+++ b/autoload/deoppet/util.vim
@@ -98,7 +98,7 @@ function! deoppet#util#_insert_text(text, next_text) abort
     setlocal nocindent
     setlocal indentexpr=
 
-    noautocmd execute 'normal!' (a:next_text ==# '' ? 'A' : 'i') . a:text
+    noautocmd execute 'normal!' (a:next_text ==# '' ? 'A' : 'a') . a:text
   finally
     let &l:autoindent = save_autoindent
     let &l:smartindent = save_smartindent
```

**Comment by Shougo** [comment]
I get it.  But your patch does not work!

Because if you applied the patch, https://github.com/Shougo/deoppet.nvim/issues/18#issuecomment-703166160 problem is occurred!

Oh, no.

**Comment by Shougo** [comment]
Can you fix both problem??
I wait your right fix.

**Comment by Shougo** [comment]
Fixed.

**Comment by e-kwsm** [comment]
Thanks again.

**Comment by Shougo** [comment]
The fix is workaround though...
